#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl

groups:
  - sudo

users:
 - name: ubuntu
 - groups: admin, sudo

system_info:
  default_user:
    groups: [sudo, admin]
    name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL

runcmd:
  - sudo usermod -aG sudo $USER
  - sudo id $USER
  - sudo hostnamectl set-hostname USER
  - sudo mkdir /tmp
  - sudo apt install python3
  - sudo apt-get install python3-pip 
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  #- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  #- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  #- sudo apt-get -y update
  #- sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  #- sudo systemctl enable docker
  #- sudo systemctl start docker.service
  #- sudo pip3 install locust
  - sudo apt install -y python3-locust
  - sudo ulimit -n 100000
  - sudo ulimit -Sn > /tmp/openfilelimit.log
  - sudo id $USER
  - touch /tmp/signal



final_message: "The system is finally up, after $UPTIME seconds"




